name: Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - ".github/**/*.yml"
      - "Dockerfile"
  workflow_dispatch:
    inputs:
      fish_version:
        description: 'Fish version to build'
        required: false
        default: '4.0.2'

env:
  IMAGE_NAME: purefish/terminal-screenshot

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        version: [
            { fish: 4.0.2, alpine: 3.22 },
        ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Extract metadata
        id: meta
        run: |
          FISH_VERSION="${{ matrix.version.fish || '4.0.2' }}"
          echo "fish_version=${FISH_VERSION}" >> $GITHUB_OUTPUT
          echo "tag=fish-${FISH_VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.tag }}
            ${{ env.IMAGE_NAME }}:latest
          build-args: |
            FISH_VERSION=${{ steps.meta.outputs.fish_version }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Test image
        run: |
          make test TAG=${{ matrix.version.fish }}
